### ISSUE TITLE
Create generic class for work with Enumerations as Entitys

### ISSUE THREAD

**Issue by andresh0816** [andresdev16/shared-kernel#3]
Would be great to create an generic class for to work with that kind of entities from enumerations, something like this:

![image](https://user-images.githubusercontent.com/20376163/227248663-64acd1f2-9105-4ba2-a9e8-3bc2a500f37a.png)

**Comment by andresh0816** [comment]
@MarkCiliaVincenti what do you think about it?

**Comment by MarkCiliaVincenti** [comment]
I'm not sure what advantages this offers over attributes.

**Comment by andresh0816** [comment]
This is a temporal solution for the need to have an enumeration with methods or behaviors. Currently C# does not support this functionality.
